---
title: "Object of Study: Wikipedia"
author: "Taylor Arnold"
output: html
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(eval = TRUE)
knitr::opts_chunk$set(fig.path = "../assets/class02-object-of-study/")
knitr::opts_chunk$set(fig.height = 5)
knitr::opts_chunk$set(fig.width = 8.5)
knitr::opts_chunk$set(out.width = "100%")
knitr::opts_chunk$set(dpi = 300)
```

## Object of Study

Our object of study for this semester (Fall 2018) concerns the edit history
of pages on Wikipedia. Our research for the semester will be guided by drawing
on questions such as:

- How is knowledge being represented through the works of an anonymous,
decentralized collective of users connected across the internet?
- What role does memory play in the representation of current and
semi-current events?
- What kinds of knowledge are privileged, or taken for granted, by
citation patterns on the internet?
- How do cultural and linguistic factors play into the structure of
Wikipedia pages (by looking at pages across different languages)?
- What role do images and other media play in the structure and
development of encyclopedic pages? Has this changed over time?

These questions can be studied from a number of disciplinary perspectives.
For example, one might draw on methods from from one or more of: psychology,
sociology, linguistics, political science, American studies, media studies,
and critical theory. In this course we will see how the methods of data
science provide a new set of tools that are able to engage with, rather than
against, these disciplinary techniques while opening the possibility of
producing knowledge through the study of large unstructured data sets.




